services:
  # Base de datos local usada por ticket-service.
  db:
    image: postgres:15-alpine
    container_name: ticket_classification_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tickets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tickets_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ticket_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    profiles:
      - ai
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ticket_network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    profiles:
      - ai
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - ticket_network

  # API REST que recibe, consulta, actualiza y elimina tickets.
  ticket-service:
    build:
      context: ./ticket-service
    container_name: ticket_service
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=tickets_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - KAFKA_BROKER=kafka:9092
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ticket_network

  # Servicio de IA que consume eventos de Kafka y clasifica tickets.
  ai-service:
    build:
      context: ./ai-service
    container_name: ai_service
    profiles:
      - ai
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - ticket_network

volumes:
  postgres_data:

networks:
  ticket_network:
    driver: bridge
